# Material Theme <https://material-theme.com/> for Helix Editor

# Syntax Highlighting

"type" = "purple"

"constructor" = "blue"

"constant" = "yellow"

"string" = "green"
"string.regexp" = "yellow"
"string.special" = "blue"

"comment" = { fg = "comment" }

"variable" = "text"
"variable.parameter" = { fg = "orange" }
"variable.builtin" = "yellow"

"label" = "orange"

"punctuation" = "cyan"

"keyword" = "purple"
"keyword.storage" = "cyan"

"operator" = "cyan"

"function" = "blue"
"function.macro" = "cyan"

"tag" = "red"
"attribute" = "purple"

"namespace" = { fg = "yellow" }

"special" = "cyan"

"markup.heading.marker" = { fg = "cyan", modifiers = ["bold"] }
"markup.heading.1" = "cyan"
"markup.heading.2" = "red"
"markup.heading.3" = "green"
"markup.heading.4" = "yellow"
"markup.heading.5" = "blue"
"markup.heading.6" = "orange"
"markup.list" = "purple"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "green", modifiers = ["underlined"] }
"markup.link.text" = "blue"
"markup.raw" = "text"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"

# User Interface

"ui.background" = { fg = "text" }
"ui.text" = { fg = "text" }
"ui.text.directory" = { fg = "blue" }

"ui.statusline" = { bg = "bg", fg = "text" }
"ui.statusline.inactive" = { bg = "bg", fg = "disabled" }
"ui.statusline.normal" = { bg = "blue", fg = "bg" }
"ui.statusline.insert" = { bg = "green", fg = "bg" }
"ui.statusline.select" = { bg = "purple", fg = "bg" }


"ui.selection" = { bg = "selection" }

"ui.linenr" = { fg = "line-number" }
"ui.linenr.selected" = { fg = "accent" }

"ui.cursor" = { bg = "highlight", fg = "white" }

"ui.cursor.primary" = { bg = "white", fg = "gray" }
"ui.cursorline.primary" = { bg = "active" }

"ui.virtual" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "highlight" }
"ui.virtual.indent-guide" = { fg = "gray" }

"ui.highlight" = { bg = "highlight" }

"ui.menu" = { bg = "highlight_dim", fg = "text" }
"ui.menu.selected" = { bg = "blue", fg = "bg" }

"ui.help" = { bg = "highlight_dim", fg = "text" }

"ui.popup" = { bg = "highlight_dim", fg = "text" }

"ui.virtual.jump-label" = { fg = "purple", modifiers = ["bold"] }

warning = "yellow"
error = "error"
info = "blue"
hint = "purple"

"diagnostic" = { underline = { color = "error", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "purple", style = "curl" } }
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"]}
"diagnostic.deprecated" = { modifiers = ["crossed_out"]}

[palette]
bg = "#25363b"
text = "#b0bec5"

white = "#eeffff"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
red = "#f07178"
purple = "#c792ea"
orange = "#f78c6c"
cyan = "#89ddff"
gray = "#546e7a"
error = "#ff5370"

disabled = "#415967"

accent = "#009688"

active = "#314549"
highlight = "#425b67"
highlight_dim = "#1e313b"

comment = "#546e7a"

selection = "#395b65"

line-number = "#48646c"
